title: Ajit Notebook
description: "A place where Ajit keeps notes useful to him and others"
url: https://ajit-y.github.io/ajit-notebook/
baseurl: ""
timezone: Europe/London
theme: jekyll-theme-cayman
permalink: pretty
repository: https://github.com/ajit-y/ajit-notebook

# Content
image_serve_path: "/assets/images"

exclude:
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock
