title: Ajit Notebook
description: "A place where Ajit keeps notes useful to him and others"
url: https://ajit-y.github.io/ajit-notebook/
# baseurl: ""
timezone: Europe/London
theme: jekyll-theme-cayman
permalink: pretty
github: [metadata]

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
