title: Ajit's Notebook
description: "A notebook"
url: https://ajit-y.github.io/ajit-notebook/
baseurl: "/ajit-notebook"
timezone: Europe/London
remote_theme: mmistakes/minimal-mistakes@4.22.0
permalink: pretty
github: [metadata]

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - publish.sh
  - package.json

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
