title: Ajit's Notebook
description: "A notebook"
url: https://ajit-y.github.io/ajit-notebook/
baseurl: "/ajit-notebook"
timezone: Europe/London
theme: minimal-mistakes-jekyll
permalink: pretty
github: [metadata]

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - publish.sh
  - package.json
